In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

from sklearn.model_selection import train_test_split
X_train,X_test, y_train , y_test = train_test_split(digits.data,digits.target,test_size=0.3)


In [34]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

c:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9537037037037037

In [35]:
svm=SVC()
svm.fit(X_train, y_train)
svm.score(X_test,y_test)

0.987037037037037

In [36]:
rf= RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9666666666666667

In [37]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [39]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [44]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test, y_test)

In [46]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

c:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9537037037037037

In [47]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.987037037037037

In [48]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9685185185185186

In [50]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [57]:
scores_1=[]
scores_svm = []
scores_rf=[]
for train_index, test_index in kf.split(digits.data):
    X_train, X_test ,y_train, y_test = digits.data[train_index],digits.data[test_index],\
        digits.target[train_index], digits.target[test_index]
    scores_1.append(get_score(LogisticRegression(),X_train, X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train, X_test,y_train,y_test))
	
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train, X_test,y_train,y_test))

c:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/m

In [58]:
scores_1

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [59]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [60]:
scores_rf

[0.9198664440734557, 0.9465776293823038, 0.9048414023372288]

In [62]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target)

c:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/m

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [63]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [65]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.93333333, 0.91111111, 0.94707521, 0.95543175, 0.91922006])

In [66]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target)

array([0.84722222, 0.80555556, 0.87465181, 0.90807799, 0.86350975])

In [69]:
cross_val_score(RandomForestClassifier(n_estimators=90 ),digits.data,digits.target)

array([0.93055556, 0.90833333, 0.9637883 , 0.96935933, 0.91922006])